### ISSUE TITLE
Add command `Add Layers from existing DCE` to `Create New Data Capture Event` 

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#210] opened 2023-04-12 09:30 UTC
A really common use case when creating a DCE is to want to base that the DCE on the same layers and methods as a previous DCE. As such, can we add a Pull-Down for `Add Layers from existing DCE` to `Create New Data Capture Event` dialog, that allows you to add to "Layers in Use" based on those used in previous DCE? I think this would have a lot of user utility and ensure that the metric tables have less "holes" on automated population. "Holes" occur where a metric can not be calculated automatically because the layers in a DCE column it depends on do not exist. 

![image](https://user-images.githubusercontent.com/9723905/231415677-c05c9cc8-17ac-428a-a598-2b08ca05e06f.png)

Assigning to @philipbaileynar first for consideration and proper scoping.

**Comment by philipbaileynar** [comment] 2023-08-01 16:40
This is duplicate of #235

**Closed by philipbaileynar** 2023-08-01 16:40 UTC
Labels: enhancement
