### ISSUE TITLE
Units in Analysis

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#385] opened 2024-05-16 15:54 UTC
Units in the analysis output would be great. An easy way would be adding it to the name of the metric. 
![image](https://github.com/Riverscapes/QRiS/assets/97305413/964c9588-8b4a-45b2-bc5b-b64b7d7ea3f5)
Since this is just displaying the name from the metric JSON, we could just include it in the name in the JSON metric file (e.g Jam Density (#/km). You can reassign to me if this seems like the best way to do it.

**Comment by joewheaton** [comment] 2024-05-21 19:37
Model after GCD please

**Comment by KellyMWhitehead** [comment] 2024-06-06 22:25
closing this as this is a duplicate of #415

**Closed by KellyMWhitehead** 2024-06-06 22:25 UTC
Labels: duplicate, enhancement
