### ISSUE TITLE
Make Surfaces appear at the Bottom of the Layer Panel when Added to QGIS

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#381] opened 2024-05-10 21:56 UTC
This is a very small and pretty insignificant tweak, but when some layers (e.g., sample frames) are imported into QGIS from QRiS, they are listed in groups below "Surfaces" and get covered up. It would be nice if all groups/layers would be above "Surfaces" so that those layers are not covered up.

**Comment by KellyMWhitehead** [comment] 2024-05-14 23:26
This is the intended behavior, and seems to be working for me, but I recognize that when things are added to the map, they don't always end up where we expect them!

I will keep an eye out for this behavior, please let me know if it consistently happening for you, or if this is an intermittent thing.

**Comment by KellyMWhitehead** [comment] 2024-05-15 00:32
Actually, I think I've figured this one out!

Should be fixed in version 0.3.20, please let me know if this is resolved.

**Closed** 2024-05-17 22:59 UTC
Labels: enhancement
