### ISSUE TITLE
Analysis feedback

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#109] opened 2022-09-20 21:42 UTC
@joewheaton can you please watch this video and provide UI feedback on QRiS analyses.

https://youtu.be/tqnc0usf9og

**Comment by joewheaton** [comment] 2022-09-21 12:57
Okay... I'm going to do these a bit at a time (as different comments)...

## The 'Analyses' Sub-Menu Organization
### The Problem
My thoughts are not real mature on this, but since I pushed you towards focusing on the individual analysis (which you have done quite nicely) , we now have a problem that this Analyses menu is going to be a mess and hard to navigate if it is based just on your user defining an analysis name. 

### A Solution
I think the solution is twofold. 

First, provide an automatic name for the user. GCD got much better when we started auto-naming based on the analysis type (just a bunch of concatenations of the choices they made). This will keep things more systematic. The user can always override this, but if we do it right, just like GCD 99% of the time they will not. This will also be the magic step to later batch processing.

Second, I think we  organize the contents under Analyses by three factors (in nested order (i.e. subfolders or nodes):

1. Analysis Type (right now, this is light saying in GCD isn't everything a damn change detection? Patience, there will be more.)
2.  Analysis Mask (name and potentially type of the polygon mask or sample frame) 
3. Analysis Segment (

So the folder or sub-folder names for the first 1 will be fixed (e.g. `Indicator Tables`). The second and third ones will be based on the feature class name in the mask library (e.g. `My Riverscape Segments`) and the unique class chosen (e.g. `Segment 1` or `Billy Bob's Reach`). 
![image](https://user-images.githubusercontent.com/9723905/191509700-5f454956-b467-4745-88bd-486935cb7914.png)

### Examples
.  In your example, there are 3 reaches in one segmentation mask. Yet, by the time you drill down, it is easy to remember where you are. Yes, you're map based highlighting will help, but I think some auto-naming and tree organization will help a ton. 

In GCD, we dealt with this by adding for the user sub-folder nodes based on either the combinations of DEMs, or the Mask names.

**Comment by joewheaton** [comment] 2022-09-21 12:58
Also your screen brightness or that dark theme is absurdly difficult to read! Change it for the next video please to light.

**Comment by joewheaton** [comment] 2022-09-21 13:54
# Analysis Metric Value Feedback

## Getting to this form
I like that you can get to this form by double clicking on right part of form (i.e.  is it row or is it the cell? I guess it is row?). However, that will not be obvious, I would prefer providing a few other ways of getting to same place. Maybe a a) right-click context menu that is verbose `Modify or Calculate this Metric`, and/or a b) a edit button or cog on right or left of each row. 

![image](https://user-images.githubusercontent.com/9723905/191516814-f02a8662-add7-47ee-8d5d-07bc82349e56.png)

## Form Label
"Analysis Metric Value" doesn't do it for me. What am I doing? I am viewing, modifying or calculating my metric!  I don't know what to call this.

## On The overall Form
Again, this form does a poor job of emphasizing what the most important thing is this powerful and helpful form does. To me the most important thing is that it gives me a way to control the calculation or estimation of individual metrics.  That's it. 

### Ideas for emphasizing this.
- Maybe the default tab is not description (that should be auto-populated from the metric library and make it easy to view the method on monitoring methods.org ). 
- Maybe the default tab is a metric viewer. It might show:
  - in really large font the value
  - in subtle font to right (the units, with an option to change on the fly without changing the metric value on disk to see same metric in different units. This is obviously inspired by GCD. This would allow a user to enter or override values in the units they are comfortable working in, but store or save the units according to the project units). 
  - in subtle downplayed way, the uncertainty associated with that.
  - a plot of where this metric value sits on a distribution of "Other Metric Values" and ability to change "Other Metric Values" between summary total (all segments (space) and DCEs (time)), all other values in this segment through different DCEs, all other segments at this same DCE. The horizontal axis is the range of values for that metric, the vertical axis is the % of values. Then a big bright dot with horizonal error bars denoting the uncertainty (if specified)
  - A box plot of the same thing described above
  -  A link to the metric definition
### Instead of "Description" change tab to Notes
Have a Notes tab with the three following sub-sections:
- Explanation for Metric Calculation Choice. We need to think this through, but this will be powerful if it has some pre-baked check box (multi) choices like:
  - Not Specified (default, but behaves like radio only it can be checked if checked)
  - Autogenerated and confirmed to be reasonable
  - Manual Override because of poor digitization/mapping
  - Manual Override because of independent field observations
  - Manual Override because of anecdotal evidence
  - Manual Override because value did not make sense
  - Manual Override for Other Reason: 
- Notes About Specific Calculation Chosen
- Log - Just a running log of the time, date, user and toggled values (only when saved to project)


### Metadata
I am not sure what this is yet.

## Uncertainty Feedback
Get over it! I know you think you hate this right now. We'll get there.

- I love how you did the Uncertainty part with the default to none, and then nice choices and the form changes based on `Plus/Minus` , `Percent`, `Min/Max`. Later we can add a feature on Min/Max to estimate this based on Min/Max for that value from all other calculations of it in that project (i.e. across segments and DCEs). 
![image](https://user-images.githubusercontent.com/9723905/191518396-3c69ddf0-8409-44db-9a6f-853fcccff47e.png)

- Don't be concerned about the "automated uncertainty". The metric is automatically calculated, the uncertainty is then specified. If it is 
- I like your suggestion of grouping (on right a boxed area for the uncertainty
- Do be concerned with storing and remembering the uncertainty object that was specified for manual or automated separately. A user may change their mind and switch back and forth between automated and manual. Remember what they did last. 
![image](https://user-images.githubusercontent.com/9723905/191518055-12208190-b24f-4d8f-b74b-2b439ee98598.png)

**Comment by joewheaton** [comment] 2022-09-21 14:05
# Feedback on Edit Analysis Properties

![image](https://user-images.githubusercontent.com/9723905/191523775-6761c5a0-1efe-4dbf-92f1-2099b5cb5859.png)
- I am getting confused about whether my analysis is making one table (i.e. for one segment of a sample frame), or multiple (i.e. it controls access to all my segments). 
- Better Form Name. This is not just an "Analysis". It is a specific type of analysis (i.e. Creating a Metric Table or Indicator Table)
- Change label from "Mask" label to "Sample Frame". Also, do not populate that by default for me (as you have here). Make me choose one. If I do not choose one, I cannot click OK only Cancel. We should emphasize thinking here about what you want to do. 
- I need to see what the "Metric Library" will allow and look like before having too much to say on the Analysis Metric Tab.
- I like pre-populating this 'Analysis Metrics'' tab table with all the Metrics from the metric library that are possible. I could see:
  -  Ability to sort (change sort order)
  - Ability to organize by groups (e.g. Protocols)
  - Default all to 'Not Used'
  - Have Button for 'Add All`
  - Later have Button for 'Load Selection' and develop a way of saving these in user profile/library
- I am struggling with whether this is the right time or place to force the choice of Indicator. I'm thinking we might be better to get people to make a good Metric Table, and then separately provide an analysis that creates an indicator table, but makes you create that from an already populated (can be partially) Metric Table. I think we're trying to squeeze too many concepts in here too efficiently. This might be one worth untangling and isolating by itself.

**Comment by joewheaton** [comment] 2022-09-21 14:11
### Feedback on "Global Calculate" Button
- It is not clear what is being calculated here. The idea you have is really good, but what am I calculating? Is it all "Values" (i.e. metrics) for a) **this** data capture event and segment, or b) *all* riverscape segments and DCEs?
- Either get a more descriptive and verbose button (guessing you will not like because of real estate) or add a more verbose tooltip, and/or give me some indication of what's happening by printing to screen or log what happens next (e.g. "Calculating x Metric for X DCE for... 
Also, can the user edit values here, or if they attempt to do so do we want that to take them to the "Analysis Metric Form"?

**Closed** 2024-09-12 22:34 UTC
Labels: help wanted
