### ISSUE TITLE
AOI clipping Issue

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#219] opened 2023-06-14 21:25 UTC
Multiple features In AOI polygon causing clipping issues with vector data. https://youtu.be/mY7zdl1plok

**Comment by KellyMWhitehead** [comment] 2023-07-31 22:31
ready for version 0.2.2

**Comment by Jdgilby** [comment] 2023-08-29 17:55
This is still persisting, but in a new way.[ Check it out](https://youtu.be/1wGsyIGCvHE)

**Comment by KellyMWhitehead** [comment] 2023-09-06 21:16
@Jdgilby is this caused by the invalid polygon geometry? I was having all kinds of trouble with that invalid catchment. Try re-running the catchment tool with the latest version (0.2.5) that cleans up the geometry and let me know if this clipping issue persists.

**Comment by Jdgilby** [comment] 2023-09-06 22:06
@KellyMWhitehead That seems to be the problem, but even fixing the geometry on it reverts it to the smaller polygon. Even if dissolving and fixing. Its weird, its like the larger part doesn't actually exist. I'll give it a shot on 0.2.5 though.

**Comment by KellyMWhitehead** [comment] 2023-12-20 22:42
@Jdgilby checking in on this issue. Has this cropped up recently? If not I will close this ticket.

**Closed** 2024-04-17 23:45 UTC
Labels: :bug: bug
